Create a seperate table for storing logs.
vulcanize/go-ethereum pull request #102
Opened 2021-08-05 05:32 UTC by arijitAD

2021-08-11 05:11 UTC, i-norden requested changes
Need to make some changes to the db schema, which will necessitate updating the go code some too, but otherwise everything looks great.

2021-08-11 05:11 UTC, i-norden commented on core/types/receipt.go
> +	LogRoot          common.Hash `json:"log_root"`
Let's use camelCase to match the other json tags

2021-08-11 05:11 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +DROP COLUMN topic3s,
Let's drop `log_contracts` too

2021-08-11 05:11 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    address               TEXT NOT NULL,
Since we use `VARCHAR(66)` for addresses everywhere else let's use it here too. For addresses we should really be doing `VARCHAR(42)` and `VARCHAR(66)` only for hashes but `VARCHAR(66)` has been grandfathered in and we should stay consistent until we decide to refactor all of them.

2021-08-11 05:11 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    block_number          BIGINT NOT NULL,
We don't need block number, we can join all the way up to the header table where it is already stored.

2021-08-11 05:11 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    block_hash            VARCHAR(66) NOT NULL,
Same for blockhash, we can get this from the header_cids table by joining log > receipt > tx > header

2021-08-11 05:11 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    tx_hash               VARCHAR(66) NOT NULL,
Same here, we get this from joining log > receipt > tx

2021-08-11 05:11 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    tx_index              INTEGER NOT NULL,
Ditto

2021-08-11 05:11 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    topic0s               VARCHAR(66)[],
These should be singular topic0, topic1, topic2, topic3 of type `VARCHAR(66)`, only one of each topic per log

2021-08-11 05:11 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    UNIQUE (block_hash, tx_hash, index)
Need `UNIQUE (receipt_id, index)` instead. For every receipt_cids entry we have one and only one log at every index in the receipt's logs array

2021-08-11 05:11 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +CREATE INDEX log_cid_index ON eth.log_cids USING btree (cid);
We'll want to replace the gin indexes below with btree indexes on the topic rows once they are `VARCHAR(66)`

2021-08-11 05:11 UTC, i-norden commented on statediff/indexer/ipfs/ipld/eth_receipt.go
> +	if first == "logs" {
We can move this into the switch statement too I think

2021-08-11 05:11 UTC, i-norden commented on statediff/indexer/ipfs/ipld/eth_receipt.go
> +	case "type":
Nice catch adding these type cases for tx and rct!

2021-08-11 05:11 UTC, i-norden commented on statediff/indexer/ipfs/ipld/eth_receipt.go
> -	case "logs":
Let's keep logs as a case

2021-08-11 05:11 UTC, i-norden commented on statediff/indexer/ipfs/ipld/shared.go
> +	MEthLog             = 0x9a
Nitpicky, but lets move this below MEthLogTrie so we keep it in hex numerical order

2021-08-11 05:59 UTC, ashwinphatak commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    topic3s               VARCHAR(66)[],
Don't we need another column for `data`?

2021-08-16 12:55 UTC, arijitAD commented on core/types/receipt.go
> +	LogRoot          common.Hash `json:"log_root"`
Done

2021-08-16 12:55 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +DROP COLUMN topic3s,
Done

2021-08-16 12:55 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    address               TEXT NOT NULL,
Done

2021-08-16 12:55 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    block_number          BIGINT NOT NULL,
Done

2021-08-16 12:55 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    block_hash            VARCHAR(66) NOT NULL,
Done

2021-08-16 12:56 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    tx_hash               VARCHAR(66) NOT NULL,
Done

2021-08-16 12:56 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    tx_index              INTEGER NOT NULL,
Done

2021-08-16 12:56 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    topic3s               VARCHAR(66)[],
Done

2021-08-16 12:56 UTC, arijitAD commented on statediff/indexer/ipfs/ipld/shared.go
> +	MEthLog             = 0x9a
Done

2021-08-16 12:56 UTC, arijitAD commented on statediff/indexer/ipfs/ipld/eth_receipt.go
> -	case "logs":
Done

2021-08-16 12:56 UTC, arijitAD commented on statediff/indexer/ipfs/ipld/eth_receipt.go
> +	if first == "logs" {
Done

2021-08-16 12:56 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +CREATE INDEX log_cid_index ON eth.log_cids USING btree (cid);
Done

2021-08-16 12:57 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    topic0s               VARCHAR(66)[],
Done

2021-08-18 12:43 UTC, i-norden approved these changes
LGTM, just one or two minor tweaks and then there are a few things still open to discussion. I'll bring these things up in slack and we can figure out what the best approach is.

2021-08-18 12:43 UTC, i-norden commented on core/types/receipt.go
> +	case DynamicFeeTxType, AccessListTxType:
Good catch, forgot this wasn't reflected here yet

2021-08-18 12:43 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    log_data            BYTEA,
Hmmm I wonder if we want to blow this out into its own row or leave it encoded in the IPLD only... log_data will be too large to put a btree index on (similar to tx_data), but it does save us from having to RLP decode the IPLD block in order to access the data...

2021-08-18 12:43 UTC, i-norden commented on statediff/indexer/indexer.go
> +		for idx, n := range logNodes {
One way we could diminish the duplication of data is to avoid publishing the standalone logs themselves as IPLDs- and only publish them as part of the log trie (which is where we need them for IPLD proofs and selectors). I think this would make sense, because I don't think we'll ever have a hash of a standalone log that we want to use to fetch a log IPLD (instead, we will have hashes of logTrie leaf nodes that contain the logs). 

Otherwise we are actually *triplicating* log data in IPLD: as part of the Receipt IPLD's log list, as part of the log trie (log trie leaf nodes contain the individual logs), and as standalone IPLDs.

2021-08-18 12:43 UTC, i-norden commented on statediff/indexer/ipfs/ipld/eth_receipt.go
> +		{Cid: commonHashToCid(MEthLog, r.LogRoot)},
Nice!

2021-08-18 12:43 UTC, i-norden commented on statediff/indexer/ipfs/ipld/eth_receipt.go
> +	return []string{"root", "status", "cumulativeGasUsed", "logsBloom", "logs", "transactionHash", "contractAddress", "gasUsed", "type"}
Let's move "type" to the front of this list to be consistent with the tx's field list, pretty arbitrary but it makes sense to have it there since the type is encoded in the first bytes of a rct/tx.

2021-08-18 12:43 UTC, i-norden commented on statediff/indexer/writer.go
> +	// TODO: Add metrics for logs.
I'll open an issue for this

2021-08-18 12:44 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    topic3s               VARCHAR(66)[],
Didn't see this til after commenting: https://github.com/vulcanize/go-ethereum/pull/102#discussion_r691190890 

If you think it is useful from a users/consumers perspective let's do it @ashwinphatak

2021-08-20 01:54 UTC, i-norden requested changes

2021-08-20 01:54 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> -    mh_key              TEXT NOT NULL REFERENCES public.blocks (key) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
So we still want a `mh_key` and `cid` that reference an IPLD block in this table, but instead of referencing a Log IPLD it should reference a LogTrie leaf node IPLD (the leaf node that contains the log this table was previously directly referencing). Does that make sense? It will be a bit involved/tricky to generate this cid/mh_key, you'll probably need to iterate over the trie we generate in `processLogs`.

2021-08-20 05:21 UTC, ashwinphatak commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    topic3s               VARCHAR(66)[],
I think it's useful if we implement the GetLogs GQL API using the log index table in https://github.com/vulcanize/ipld-eth-server/pull/92, so we don't have to read it from elsewhere?

We haven't done that yet in the linked PR in ipld-eth-server. We should return the log CID and ipld block there, maybe also the receipt CID in a new field.

2021-08-20 05:40 UTC, ashwinphatak commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    topic3s               VARCHAR(66)[],
@i-norden While doing this, would it make sense to filter out "failed" logs (based on the receipt status) here: https://github.com/vulcanize/ipld-eth-server/blob/master/pkg/graphql/graphql.go#L1031

2021-08-23 16:42 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> -    mh_key              TEXT NOT NULL REFERENCES public.blocks (key) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
Done

2021-08-24 02:14 UTC, i-norden reviewed
Thanks Arijit, this is looking good. A few comments, nothing major. But I'm curious if we have proper unit test coverage for the indexing of the logs table, that includes the new `mh_key` and `cid` rows? I don't see it in this diff, might have missed it.

2021-08-24 02:14 UTC, i-norden commented on statediff/indexer/indexer.go
> +			logCID[idx] = id
Do we need to reallocate the log CIDs to this new logCID slice, can't we use the slice in args.logLeafNodeCIDs?

2021-08-24 02:14 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    cid                 TEXT NOT NULL,
I think we should rename this to leaf_cid, to make it clear our CID no longer references a log directly but rather the leaf node that contains it. What are your thoughts on that @ashwinphatak?

2021-08-24 02:14 UTC, i-norden commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    mh_key              TEXT NOT NULL REFERENCES public.blocks (key) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
And same here, we could rename this to "leaf_mh_key" to make an explicit distinction.

2021-08-24 02:14 UTC, i-norden commented on statediff/indexer/indexer.go
> +				CID:     logCID[idx],
Related to the above comment, couldn't this be `args.logLeafNodeCIDs[i][idx]`?

2021-08-24 02:18 UTC, i-norden approved these changes

2021-08-24 05:24 UTC, ashwinphatak commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    cid                 TEXT NOT NULL,
Yes, makes sense.

2021-08-24 10:05 UTC, arijitAD commented on statediff/indexer/indexer.go
> +			logCID[idx] = id
Done

2021-08-24 10:07 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    cid                 TEXT NOT NULL,
Done

2021-08-24 10:07 UTC, arijitAD commented on statediff/db/migrations/00016_create_eth_log_cids_table.sql
> +    mh_key              TEXT NOT NULL REFERENCES public.blocks (key) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
Done

2021-08-24 10:09 UTC, arijitAD commented on statediff/indexer/indexer.go
> +				CID:     logCID[idx],
Done

2021-08-24 10:56 UTC, ashwinphatak approved these changes

2021-08-24 11:41 UTC, arijitAD commented
Will merge this PR once we have a major release https://github.com/vulcanize/go-ethereum/pull/107

2021-08-27 07:20 UTC, merged