Report DB metrics
vulcanize/go-ethereum pull request #140
Opened 2021-10-21 11:56 UTC by arijitAD

https://github.com/vulcanize/go-ethereum/issues/138

2021-10-21 13:16 UTC, i-norden approved these changes

2021-10-22 13:37 UTC, i-norden approved these changes
LGTM. Has this been tested?

2021-10-22 13:39 UTC, i-norden requested changes

2021-10-22 13:39 UTC, i-norden commented on statediff/service.go
> +		if metrics.Enabled {
ReportDBMetrics checks if metrics.Enabled is true and exits if not, so we don't need to check here.

2021-10-22 13:48 UTC, arijitAD commented on statediff/service.go
> +		if metrics.Enabled {
Done

2021-10-22 13:50 UTC, i-norden commented on statediff/service.go
> +		if metrics.Enabled {
Thanks! Have you had a chance to run/test with this enabled?

2021-10-26 11:24 UTC, arijitAD commented on statediff/service.go
> +		if metrics.Enabled {
![Screenshot 2021-10-26 at 4 53 39 PM](https://user-images.githubusercontent.com/5843604/138868274-8177c1d7-579a-4ff0-bd4a-6e13c6c88750.png)
Verified in Prometheus

2021-10-26 11:24 UTC, merged