Add a flag to start processing statediff if we are caught up to the head of the chain
vulcanize/go-ethereum pull request #205
Opened 2022-03-10 18:14 UTC by abdulrabbani00

# Overview
This PR will allow users to add a flag when starting geth, indicating if we should wait for the statediff service to catch up to the head of the chain. 

* The feature has been tested using dapptools.
* The feature includes unit tests.
* The feature has __not__ been tested with mainnet data.
* The feature has __not__ been tested for performance.

# Data Structure Changes

This feature changes two major data structures used in the statediffing service.
1. `statediff/config.go` - `Config` 
  a. `WaitforSync` - This change allows us to indicate if the statediff service should wait for us to catch up to head.
2.  `statediff/service.go` - `Service`
  a. `WaitforSync` - This change allows us to indicate if the statediff service should wait for us to catch up to head.
  b. `Backend` - This backend object is necessary to query the internal API, which indicates if we have caught up to the head of the chain.

These changes have not failed any of the current unit tests under `/statediff.`

# Testing

This PR includes two unit tests. These unit tests have a new mock called `Backend.` The tests make sure that we catch up to head properly before indicating that we are all caught up.

We should test this with production data to ensure the feature is working correctly and does not incur any performance issues.

2022-03-16 20:23 UTC, i-norden requested changes
Looks great! Just a few comments for some very minor non-functional changes.

2022-03-16 20:23 UTC, i-norden commented on statediff/README.md
> +`--statediff` flag is used to turn on the service
Without the 2 spaces after each line these show up all on the same line when viewing the readme in github.

2022-03-16 20:23 UTC, i-norden commented on statediff/service.go
> +	syncStatus, err := pubEthAPI.Syncing()
We can just return `pubEthAPI.Syncing()` directly unless we want to wrap additional context around the `err` or we want to resolve the `interface{}` to True or False and return `(bool, error)` instead.

2022-03-16 20:23 UTC, i-norden commented on statediff/service.go
> +	for !Synced {
We should use a `time.Ticker` here to only poll at some short interval like 1 second.

2022-03-16 20:23 UTC, i-norden commented on statediff/service_test.go
> +		//t.Log("Backend: ", backend)
nitpick: clean up these commented our loggings

2022-03-16 20:23 UTC, i-norden commented on statediff/service_test.go
> +			t.Error("checkSyncComplete is empty: ", len(checkSyncComplete))
nitpick: I think the only way it'd reach this code path is if if `len(checkSyncComplete)` was somehow > 1, not empty (due to the 3 guards starting on line 403). Which is to say idt this code path is possible, so not sure we need the `if len(checkSyncComplete) == 1` check on line 427.

2022-03-16 20:23 UTC, i-norden commented on statediff/service_test.go
> +func testGetSyncStatus(t *testing.T) {
Nice, this unit test is very well formulated/structured!

2022-03-18 12:08 UTC, abdulrabbani00 commented on statediff/service_test.go
> +			t.Error("checkSyncComplete is empty: ", len(checkSyncComplete))
Good catch there. Sharp eye 👁️

2022-03-18 12:09 UTC, abdulrabbani00 commented on statediff/README.md
> +`--statediff` flag is used to turn on the service
Thank you, not sure why my markdown formatted disrespected me like this.

2022-03-18 12:27 UTC, abdulrabbani00 commented on statediff/service.go
> +	syncStatus, err := pubEthAPI.Syncing()
I've made two changes:

1. I handle the error in the `Start` function. The error from `GetSyncStatus` gets passed all the way to the top.
2. I return a bool instead of an `interface`. At this point, the interface is not useful, but there could be a day when the information in the interface is useful (it provides a rich map of the state of the chain when the sync occurred).

2022-03-18 12:27 UTC, abdulrabbani00 commented on statediff/service_test.go
> +func testGetSyncStatus(t *testing.T) {
Thank you sir :D

2022-03-18 13:16 UTC, i-norden approved these changes
LGTM! Thanks for making the updates.

2022-03-18 13:44 UTC, merged