Statediff into postgres
vulcanize/go-ethereum pull request #30
Opened 2020-10-21 13:22 UTC by roysc

This provides a new RPC method `statediff_WriteStateDiffAt` to write diffs directly into PostgreSQL upon client request (per https://github.com/vulcanize/eth-statediff-service/issues/11). To do this, I copied over and refactored some of the tooling from https://github.com/vulcanize/ipld-eth-indexer.

@i-norden How should we merge the code hash & storage output from https://github.com/vulcanize/go-ethereum/pull/27? I suppose it depends on how that data is consumed.

More minor questions:
* I added three new CLI parameters to pass in the DB connection URI, node ID, and client name. It may be cleaner to pass these as a single comma separated string or even a separate toml file.
* Do we still want to configure the max open/idle/lifetime DB parameters, or leave these at default for now?
* "Transformer" is not really appropriate anymore, maybe DBWriter?
* I'm not sure it will be possible to perform writes concurrently and still wrap them in an atomic transaction - I suspect not, but haven't found a definitive answer.

2020-10-22 03:23 UTC, i-norden reviewed
I still need a chance to take a closer look at the code but so far this looks great! In regards to those questions:

* One option is to go ahead and rebase this on top of the latest state of statediff_at_anyblock-1.9.11, which shouldn't be _too_ messy since we touched mostly different sections of code, and then merge this and apply the code=>codehash update in a separate PR.
* I think the CLI params like that is good. If anything I'd recommend splitting the URI out into separate CLI flags (hostname, port, database, user, password). 
* I think leaving open/idle/lifetime as default is fine for now, and we can add stuff like that in other PRs to keep this one more focused (already a very significant change w/ large diff!) 
* Agree on Transformer name- DBWriter makes more sense. Or what do think about renaming the current Indexer to DBWriter/PGWriter and the Transformer to Indexer?
* Yeah it's not possible to write to a single sql.Tx from within separate goroutines, unfortunately. So it would require some additional rework to be able to use the concurrent iterator, but I think it's still possible e.g. we could have all the separate goroutines of the concurrent builder/iterator send their processed StateNode objects out a single channel where a lone worker writes them into a single transaction.

2020-10-23 10:12 UTC, roysc commented
* Roger on rebasing for code/hash stuff
* I'll leave the CLI like it is then, but if we change it I think I would vote for using a separate toml file just in the name of cleanliness of config handling (and allowing to reuse config files for the indexer service)
* Agreed on naming, and in that case I may also want to rename the indexer's methods from `index*CID` to `merge*CID` or `upsert*CID`, to be more direct
* Yeah, consuming thread + channels should work, and still improve performance. I would also really prefer to merge this and the standalone statediff service into a single codebase once we get to that point.

2020-10-23 12:06 UTC, AFDudley commented
>Yeah, consuming thread + channels should work, and still improve performance. I would also really prefer to merge this and the standalone statediff service into a single codebase once we get to that point.

Sooner rather than later, please.

2020-10-23 13:41 UTC, i-norden commented
Will try to finish up my review today @roysc

2020-10-23 14:36 UTC, roysc commented
Alright, I incorporated the SQL output tests from `ipld-eth-indexer` and otherwise this is pretty much covered by the existing test suite since it's behind the original Builder interface.

What remains - 
* handling the code & code hash, we could just copy over how it's handled in the indexer, but if that output is significant enough it can also be done iteratively
* we will need to trigger these write calls from somewhere - I have some basic code in the `ipld-eth-indexer` to test it

@AFDudley I can start on concurrency as soon as we merge this.

2020-10-26 13:04 UTC, i-norden requested changes
Looks great! The main thing is that we need to add a new service loop that automatically writes diffs at the head of chain. Only a couple small comments aside from that.

Eventually we'll want to figure out a better way of sharing packages between this and ipld-eth-indexer (use a 3rd repo for some stuff).

And eventually we should convert these ported tests away from ginkgo/gomega since go-ethereum uses the standard lib test package.

2020-10-26 13:04 UTC, i-norden commented on statediff/service.go
> +
We need another method that we turn on by CLI param, which automatically writes statediffs to Postgres as they stream off the chainEvents channel of the syncing chain. This will look almost exactly like `Loop()` method on line 154, except instead of sending the diff to subscribers it writes directly to Postgres.

2020-10-26 13:04 UTC, i-norden commented on statediff/indexer/postgres/config.go
> +	DATABASE_NAME                 = "DATABASE_NAME"
Note: this doesn't need to be resolved now

2020-10-26 14:33 UTC, roysc commented on cmd/utils/flags.go
> +func RegisterStateDiffService(stack *node.Node, dbParams *[3]string) {
Definitely - this was a bit of a punt, meant to write a TODO

2020-10-26 14:34 UTC, roysc commented on statediff/service.go
> +
Makes sense - would that just be triggered via CLI or also toggleable by an RPC call?

2020-10-26 16:53 UTC, i-norden commented on cmd/utils/flags.go
> +func RegisterStateDiffService(stack *node.Node, dbParams *[3]string) {
Cool cool yeah this doesn't need to be done now

2020-10-26 16:53 UTC, i-norden commented on statediff/service.go
> +
I think just turn it on by CLI is fine for now

2020-10-26 16:55 UTC, i-norden commented
@roysc Btw I don't think we should try to port the concurrency stuff into here at this time, there will be data races with the regular ongoing sync process plus the statediff service needs to operate through the same StateDB object as the BlockChain to utilize it's in-memory cache. This another reason to maintain the separate repos IMO.

2020-11-04 16:48 UTC, i-norden commented
Hey @roysc, tested this locally and it appears to be working!

Using
`./build/bin/geth --syncmode=full --gcmode=archive --statediff --statediff.writing --statediff.db=postgres://localhost:5432/vulcanize_testing?sslmode=disable --statediff.dbnodeid=yeee --statediff.dbclientname=yooo` 

Seeing results in every cid table (including uncles and receipts)

2020-11-04 16:51 UTC, i-norden approved these changes
Noting some changes that don't necessarily need to be made in this PR.

2020-11-04 16:51 UTC, i-norden commented on statediff/indexer/shared/functions.go
> +	"github.com/sirupsen/logrus"
We should update all the ported packages to use Geth's log package

2020-11-04 16:51 UTC, i-norden commented on statediff/indexer/indexer.go
> +			log.Info(traceMsg)
We should change this to the Debug level

2020-11-04 16:52 UTC, i-norden commented on statediff/indexer/shared/functions.go
> +	"github.com/sirupsen/logrus"
Similarly, we should update any tests we ported over to use the default test pkg that the rest of geth uses instead of ginko/gomega

2020-11-05 14:41 UTC, roysc commented
@i-norden Refactored the logging and tests - (btw. noticed we have the gomega module [vendored in](https://github.com/vulcanize/go-ethereum/tree/statediff_at_anyblock-1.9.11/vendor/github.com/onsi/gomega), guessing we can remove it).

2020-11-05 15:30 UTC, i-norden commented
@roysc yes please get rid of the vendor/ dir

2020-11-11 16:25 UTC, i-norden approved these changes
LGTM. I think we should go ahead and merge this so we can cut a release and apply the rebase on top. Running it locally things look good and I have confirmed the codehash=>code is being stored correctly. There is a pretty big lag between the head in the Postgres db and the head of the current block import but I'm not surprised considering how quickly it imports chunks of blocks while catching up to head and the limiting resources of my computer.

2020-11-11 16:26 UTC, merged