[WIP] statediff: Use a worker pool
vulcanize/go-ethereum pull request #43
Opened 2020-11-19 12:35 UTC by roysc

Changes statediff service to spawn a pool of workers each running an independent `WriteLoop`.

* Number of workers is configured with a new `statediff.workers` CLI flag.
* Expands the lastBlock cache to use a map of hashes to blocks, with a max size also limited to the number of workers.
* Geth uses an internal cache for receipts and other data; this causes a data race to be detected inside `receipts.DeriveFields()` when used during indexing, though I didn't debug this deeply enough to find out why the same receipts data would ever be touched by goroutines which should only be working on separate blocks.
* There is still a data race issue in the Trie data access, probably due to the `state.Database` hitting its cache limit.

2020-11-20 10:51 UTC, roysc commented
Running this on a fresh full chain, I'm not able to reproduce the trie node errors I was seeing before, so they may not be directly related - removing the WIP tag.

2020-11-24 08:47 UTC, i-norden requested changes
Looks great! A few comments but only one or two changes. Running locally everything seem to be working (ran with 4 and 8 workers, around block 80,000). I do see some errors on shutdown that I think are new but also probably inconsequential:
`WARN [11-24|02:40:55.972] Error from chain event subscription      error=nil
WARN [11-24|02:40:56.031] Error from chain event subscription      error=nil
WARN [11-24|02:40:56.032] Error from chain event subscription      error=nil`

Are you still seeing a Trie data race issue on your end?

I haven't benchmarked, it would be good to get a rough estimate on performance impact.

2020-11-24 08:47 UTC, i-norden commented on statediff/service.go
> +	chainEventCh <-chan core.ChainEvent
When integrating with the metrics we might want to have an intermediate `select` loop that logs the metric off the primary core.ChainEvent channel before passing the event along to a secondary worker queue channel here, if we want to avoid logging metrics from within worker goroutines.

2020-11-24 08:47 UTC, i-norden commented on statediff/service.go
> +	{
Brackets and comment can go I think

2020-11-24 08:47 UTC, i-norden commented on statediff/service.go
> +			CopyReceipt(&newrct, rct)
This is simpler and appears to be working when I run locally:

```go
newRct := new(types.Receipt)
*newRct = *rct
receipts = append(receipts, newRct)
```

2020-11-24 13:54 UTC, roysc commented on statediff/service.go
> -func (lbc *lastBlockCache) replace(currentBlock *types.Block, bc blockChain) *types.Block {
I checked and the hit/access ratio is very close to 1, so it does still seem to be helping, I can verify further with benchmarks.

2020-11-24 13:58 UTC, roysc commented on statediff/service.go
>  		parentBlock = bc.GetBlockByHash(parentHash)
My reasoning was that two blocks shouldn't be processed with the same parent block, so we just cache the current one so it's available when its child block gets processed. I did some logging to verify this - blocks are accessed no more than once. Also, the number of misses is so low that hardly any parents would get added to the cache (since we would only add them on a miss).

2020-11-24 14:04 UTC, roysc commented on statediff/service.go
> +	{
oh yeah, meant to clean it up

2020-11-24 16:05 UTC, roysc commented on statediff/service.go
> +			CopyReceipt(&newrct, rct)
It's odd - I was getting a data race detected at various points in [this loop](https://github.com/vulcanize/go-ethereum/blob/v1.9.24-statediff/core/types/receipt.go#L306), but now I can't reproduce it even on that branch. That was the reason for the deep copy before, but now it seems even the shallow copy is not necessary, so I can revert those changes.

2020-11-24 16:08 UTC, roysc commented on statediff/service.go
> +	chainEventCh <-chan core.ChainEvent
Done, after rebasing on [this branch](https://github.com/vulcanize/go-ethereum/pull/44)

2020-11-25 02:03 UTC, i-norden commented on statediff/service.go
> -func (lbc *lastBlockCache) replace(currentBlock *types.Block, bc blockChain) *types.Block {
Oh that's awesome, thanks for checking that!

2020-11-25 02:11 UTC, i-norden commented on statediff/service.go
>  		parentBlock = bc.GetBlockByHash(parentHash)
Ah yeah that makes sense, and is generally true. The only time this wouldn't be true is when there are reorg while syncing at the head of chain (will never see it happen during chain import e.g. during any of our local tests). I think in that case it is likely still better to need to reach past the cache to retrieve the block rather than to waste cache space on the off chance. We'd need to benchmark at head to really pin down the tradeoff.

2020-11-25 02:17 UTC, i-norden approved these changes
LGTM! Feel free to merge.

2020-11-25 10:29 UTC, roysc commented
The chain event subscription error seems to be from the workers receiving the close of the error channel before the quit channel. Like you said, doesn't seem to indicate a real problem, though.

2020-11-25 10:29 UTC, merged