Merge v1.10.4-statediff-0.0.23 to v1.10.4-statediff
vulcanize/go-ethereum pull request #85
Opened 2021-06-22 10:35 UTC by arijitAD

2021-06-23 14:18 UTC, i-norden reviewed
Hey Arijit you are already on it but I should have noticed that since v1.10.4 has eip1559 added this rebase becomes much more complicated as we need to do #80

2021-06-30 00:54 UTC, i-norden requested changes
Looking good, left comments below on the specific changes requested. The main thing is that we need to be sure to still handle pre-EIP-1559 headers that have a nil `BaseFee` (and have test cases for it).

2021-06-30 00:54 UTC, i-norden commented on statediff/builder_test.go
> +		Balance:  big.NewInt(3999629697375000000),
I thought using these variables helped demonstrate the reason the balance is what it is, what's the reason for using inline values?

2021-06-30 00:54 UTC, i-norden commented on statediff/db/migrations/00004_create_eth_header_cids_table.sql
> +  base_fee              BIGINT NOT NULL,
This should not be `NOT NULL` because it will be null for records before the EIP-1559 fork.

2021-06-30 00:54 UTC, i-norden commented on statediff/indexer/indexer.go
> +		BaseFee:         header.BaseFee.String(),
Similarly, `header.BaseFee` will be nil for headers before the EIP-1559 fork and so this will panic.

2021-06-30 00:54 UTC, i-norden commented on statediff/indexer/mocks/test_data.go
> +		BaseFee:     big.NewInt(params.InitialBaseFee),
We should probably keep a test (and mockBlock) for a block before the EIP-1559  fork, when `BaseFee` will be nil.

2021-06-30 00:54 UTC, i-norden commented on statediff/indexer/indexer.go
It won't let me tag the line since it's not part of this diff, I'm not sure when it was added, but on line 339 we do not need a type definition for `AccessListElementModel`.

2021-07-01 06:11 UTC, arijitAD commented on statediff/builder_test.go
> +		Balance:  big.NewInt(3999629697375000000),
Yes, But the mining reward and the gas fee charged seems to vary. Is there a way to predict it accurately?

2021-07-01 06:11 UTC, arijitAD commented on statediff/db/migrations/00004_create_eth_header_cids_table.sql
> +  base_fee              BIGINT NOT NULL,
Done

2021-07-01 06:12 UTC, arijitAD commented on statediff/indexer/indexer.go
> +		BaseFee:         header.BaseFee.String(),
Added legacy Txn test for backward compatibility.

2021-07-01 06:12 UTC, arijitAD commented on statediff/indexer/mocks/test_data.go
> +		BaseFee:     big.NewInt(params.InitialBaseFee),
Added legacy Txn test for backward compatibility.

2021-07-01 06:15 UTC, arijitAD commented on statediff/indexer/indexer.go
Removed

2021-07-01 06:19 UTC, arijitAD commented
<img width="929" alt="Screenshot 2021-07-01 at 11 32 12 AM" src="https://user-images.githubusercontent.com/5843604/124075280-4093a480-da62-11eb-90c8-b765939b0885.png">
Legacy Txn test failing before the `base_fee` column type change. It passes now.

2021-07-01 13:00 UTC, i-norden commented on statediff/indexer/mocks/test_data.go
> +		BaseFee:     big.NewInt(params.InitialBaseFee),
You mean legacy header test?

2021-07-01 13:17 UTC, i-norden commented on statediff/indexer/mocks/test_data.go
> +		BaseFee:     big.NewInt(params.InitialBaseFee),
I'm kind of confused, we already had tests for legacy txs and receipts. We just needed to add back the test for the header without `BaseFee`.

2021-07-01 13:19 UTC, i-norden requested changes

2021-07-01 13:19 UTC, i-norden commented on statediff/db/migrations/00004_create_eth_header_cids_table.sql
> +  base_fee              VARCHAR(38),
We should keep this as `BIGINT`.

2021-07-01 13:19 UTC, i-norden commented on statediff/indexer/indexer.go
> +		BaseFee:         header.BaseFee.String(),
You mean legacy header test? I'm kind of confused, we already had tests for legacy txs and receipts. We just needed to add back the test for the header without BaseFee.

2021-07-01 13:20 UTC, i-norden commented on statediff/indexer/mocks/test_data.go
> +		BaseFee:     big.NewInt(params.InitialBaseFee),
You mean legacy header test? I'm kind of confused, we already had tests for legacy txs and receipts. We just needed to add back the test for the header without BaseFee.

2021-07-01 13:21 UTC, i-norden requested changes

2021-07-01 13:21 UTC, i-norden commented on statediff/indexer/indexer.go
> +		BaseFee:         header.BaseFee.String(),
This still needs to be fixed. For header's before the EIP-1559 upgrade, `header.BaseFee` will be `nil` and so trying to access this `String()` method on it will panic.

2021-07-01 15:16 UTC, arijitAD commented on statediff/indexer/indexer.go
> +		BaseFee:         header.BaseFee.String(),
This won't happen because `bigInt` internally checks for nil.
https://github.com/golang/go/blob/9d65578b83f0d52f0d2f526212dd3b4ee1a5f031/src/math/big/intconv.go#L22
```
func TestBH(t *testing.T) {
	header := &Header{}
	fmt.Println(header.BaseFee.String())
}
```
Wrote this test to verify. It returns `nil`

2021-07-01 15:38 UTC, arijitAD commented on statediff/db/migrations/00004_create_eth_header_cids_table.sql
> +  base_fee              VARCHAR(38),
Done

2021-07-01 15:40 UTC, arijitAD commented on statediff/indexer/indexer.go
> +		BaseFee:         header.BaseFee.String(),
This doesn't panic for `String()` because `bigInt` handles nil value in a string. But it panics for `int64`. I have added a check.

2021-07-01 16:06 UTC, i-norden commented on statediff/indexer/indexer.go
> +		BaseFee:         header.BaseFee.String(),
Oh I'm sorry I doubted, thanks for clarifying that! If it doesn't panic on `String()` for `nil` BigInt then we don't need a check.

2021-07-01 16:07 UTC, i-norden approved these changes
LGTM!!

2021-07-01 16:19 UTC, closed without merging

2021-07-01 16:21 UTC, arijitAD commented
Closing this in favour of https://github.com/vulcanize/go-ethereum/pull/93